# Generated by Django 5.1.3 on 2024-12-29 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='employee',
        #     name='company',
        #     field=models.CharField(blank=True, max_length=50, null=True),
        # ),
        # migrations.AddField(
        #     model_name='employee',
        #     name='date_of_joining',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='employee',
        #     name='department',
        #     field=models.CharField(blank=True, max_length=50, null=True),
        # ),
        # migrations.AddField(
        #     model_name='employee',
        #     name='employee_id',
        #     field=models.CharField(blank=True, max_length=20, null=True),
        # ),
        # migrations.AddField(
        #     model_name='employee',
        #     name='mobile',
        #     field=models.CharField(blank=True, max_length=11, null=True),
        # ),
        # migrations.AddField(
        #     model_name='employee',
        #     name='user',
        #     field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='employee',
        #     name='designation',
        #     field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('hr', 'HR')], max_length=50),
        # ),
        # migrations.AlterField(
        #     model_name='employee',
        #     name='name',
        #     field=models.CharField(max_length=50),
        # ),
    ]
