# Generated by Django 5.1.3 on 2024-12-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_employee_company_employee_date_of_joining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('admin', 'Admin'), ('mechanic', 'Mechanic'), ('supervisor', 'Supervisor'), ('hr', 'HR')], max_length=50),
        ),
    ]
