# Generated by Django 5.1.4 on 2024-12-31 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_employee_designation'),
        ('user_management', '0004_employee_company_employee_date_of_joining_and_more'),
    ]

    operations = [
    ]
