# Generated by Django 5.1.4 on 2025-01-04 16:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_address_company_contact_number_company_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='company',
            name='industry_type',
            field=models.CharField(choices=[('RMG', 'Ready-Made Garments'), ('Textiles', 'Textiles'), ('Other', 'Other')], default='RMG', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
