# Generated by Django 5.1.4 on 2025-01-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='owner_name',
        ),
    ]
