# Generated by Django 5.1.4 on 2025-01-04 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_company_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
