# Generated by Django 5.1.4 on 2025-01-04 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_remove_company_contact_number_company_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk', models.CharField(max_length=30)),
                ('floor_no', models.CharField(blank=True, max_length=50, null=True)),
                ('line_no', models.CharField(blank=True, max_length=50, null=True)),
                ('room', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=40)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
