# Generated by Django 5.1.4 on 2025-01-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='slug',
        ),
    ]
